def contact_email_template(name: str, email: str, phone: str, message: str, subject: str):
    
    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <style>
            body {{
                font-family: Arial, sans-serif;
                line-height: 1.6;
                color: #333;
            }}
            .container {{
                max_width: 600px;
                margin: 0 auto;
                padding: 20px;
                background-color: #f9f9f9;
                border: 1px solid #ddd;
                border-radius: 5px;
            }}
            .header {{
                background-color: #007bff;
                color: #fff;
                padding: 10px;
                text-align: center;
                border-radius: 5px 5px 0 0;
            }}
            .content {{
                padding: 20px;
                background-color: #fff;
                border: 1px solid #eee;
            }}
            .footer {{
                text-align: center;
                margin-top: 20px;
                font-size: 0.9em;
                color: #777;
            }}
            .field {{
                margin-bottom: 10px;
            }}
            .label {{
                font-weight: bold;
            }}
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h2>New Contact Us Enquiry</h2>
            </div>
            <div class="content">
                <p>Hello Admin,</p>
                <p>You have received a new enquiry from the website "Contact Us" form.</p>
                
                <div class="field">
                    <span class="label">Subject:</span> {subject}
                </div>
                
                <div class="field">
                    <span class="label">Name:</span> {name}
                </div>
                
                <div class="field">
                    <span class="label">Email:</span> {email}
                </div>
                
                <div class="field">
                    <span class="label">Phone:</span> {phone}
                </div>
                
                <div class="field">
                    <span class="label">Message:</span><br>
                    {message}
                </div>
            </div>
            <div class="footer">
                <p>This email was automatically generated by Prime Zone Media Smart Form.</p>
            </div>
        </div>
    </body>
    </html>
    """
    return html
